name: DEV - Tutorial Backend Deploy

on:
  repository_dispatch:
    types: [kai-tutorial-backend-cd-dev]
  workflow_dispatch:

env:
  REPOSITORY: "superkookai/kai-tutorial-backend"
  APP_NAME: kai-tutorial-backend
  AZURE_WEB_APP_NAME: app-kai-tutorial-backend-dev-001
  CONTAINER_REPOSITORY: "acrkaitutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  build-and-deploy-app-service:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: "Checkout pipelines"
      uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        allow-no-subscriptions: true
    - name: 'Set subscription'
      run: az account set --subscription e5208964-08b0-43f8-a6be-e21f4980a3d7
    - name: "Deploy to Azure WebApp"
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        images: '${{ env.CONTAINER_REPOSITORY }}/${{ env.APP_NAME }}:${{env.IMAGE_TAG}}'
    - name: Set Web App Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        app-settings-json: |
          [
            {
              "name": "MONGODB_CONNECTION_STRING",
              "value": "mongodb://cosmos-kai-tutorial-001:Eyx1QHSV6gZrFjFkq39MjRaa1541MkJ20vq3OZkOo5mGgJYQwlreLMleDptkNvlGnybi8TrUhG992atRPnKMNA==@cosmos-kai-tutorial-001.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cosmos-kai-tutorial-001@",
              "slotSetting": false
            },
            {
              "name": "PORT",
              "value": 80,
              "slotSetting": false
            }
          ]